#!/bin/bash

export WORKON_HOME=$HOME/bin/Python_Virtual_Envs

PS1='\A  \h  \W > '

alias ssh="ssh -o ServerAliveInterval=60"
# Save and reload the history after each command finishes
export HISTCONTROL="ignoreboth:erasedups" # no duplicate entries, cmds wth space
shopt -s histappend
export PROMPT_COMMAND="history -n; history -w; history -c; history -r; $PROMPT_COMMAND"
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'
export HISTSIZE=10000                   # big big history
export HISTFILESIZE=10000               # big big history
alias nohup="nice -19 nohup"
alias rsyncGup="rsync -au --delete --exclude .git --exclude *.pyc --exclude SRS --exclude usageScripts --exclude .gitignore ~/GUP/gup/ /isitools/GUP"
alias vi="/isitools/vim8/bin/vim"


if [ $onMac == 'true' ] 
then 
    alias vi=mvim
    export PATH="/Users/jsteill/anaconda/bin:$PATH"
    # Setting PATH for Python 3.5
    # The orginal version is saved in .bash_profile.pysave
    PATH="/Library/Frameworks/Python.framework/Versions/3.5/bin:${PATH}"
    export PATH
    alias mysql="/Applications/MAMP/Library/bin/mysql"
    exit 1
fi

# -----------------------   For MIR Machines: -------------------------------

function see_ls_colors {
    IFS=:     
    for i in $LS_COLORS     
    do        
     echo -e "\e[${i#*=}m$( x=${i%=*}; [ "${!x}" ] && echo "${!x}" || echo "$x" )\e[m" 
    done       
}

function tar_gd {
    tar -czf "$1.tgz" "$1"
    mv "$1.tgz" ~/GUP/Results_Delivered/
}
export -f tar_gd

path_append ()  { path_remove $1; export PATH="$PATH:$1"; }
path_prepend () { path_remove $1; export PATH="$1:$PATH"; }
path_remove ()  { export PATH=`echo -n $PATH | awk -v RS=: -v ORS=: '$0 != "'$1'"' | sed 's/:$//'`; }
path_remove_ld ()  { export LD_LIBRARY_PATH=`echo -n $LD_LIBRARY_PATH | awk -v RS=: -v ORS=: '$0 != "'$1'"' | sed 's/:$//'`; }

function use_Bowtie() {
    if [ $# -eq 1 ]
    then
        Bver=$1
    else
        Bver="1.2.2"
    fi
    B="bowtie-$Bver"
    export PATH="/isitools/$B:$PATH"
    echo "Using $B"
}
export -f use_Bowtie

### use pigz
gzip() {
    pigz "$@"
}
export -f gzip
gunzip() {
    unpigz "$@"
}
export -f gunzip

alias envp="source ~/.pyVirt/env/bin/activate"
alias envp_off="source ~/.pyVirt/env/bin/deactivate"
alias p366="use_Python 3.6.6; export PYTHONPATH=$HOME/GUP/gup/:$PYTHONPATH; cd ~/PROJ ; source $WORKON_HOME/P366/bin/activate"
alias p366="use_Python 3.6.6; cd ~/GUP ; source $WORKON_HOME/P366/bin/activate"
alias pta="python -m unittest discover"
alias aa8="autopep8 --in-place --aggressive --aggressive "
alias aa8g="autopep8 --in-place --aggressive --aggressive $HOME/GUP/gup/*.py $HOME/GUP/gup/gup/*.py $HOME/GUP/gup/gup/tests/*.py"
use_Bowtie 

