#!/bin/bash
export PERL_LOCAL_LIB_ROOT=/isitools/perl5.10.1/lib/5.10.1 
export PERL_MB_OPT=/isitools/perl5.10.1/lib/5.10.1
export PERL_MM_OPT=INSTALL_BASE=/isitools/perl5.10.1/lib/5.10.1
export PERL5LIB='/isitools/perl5.10.1/lib/5.10.1/lib/perl5:/isitools/perl5.10.1/lib/5.10.1/x86_64-linux:/isitools/perl5.10.1/lib/5.10.1:/isitools/perl5.10.1/lib/5.10.1/x86_64-linux-thread-multi-ld:/usr/lib64/perl5'
export PATH=/isitools/perl5.10.1/bin:$PATH:
export PATH=/isitools:/isitools/perl5.10.1/bin:/isitools/perl5.10.1/lib:$PATH

export PERL_LOCAL_LIB_ROOT="$HOME/lib/perl5"
function delete_local_perl {
    rm -rf $HOME/.cpan $HOME/.local/share/.cpan $PERL_LOCAL_LIB_ROOT/*
}
export -f delete_local_perl

function install_local_perl {
    delete_local_perl
    use_perl_518;
    mkdir -p $PERL_LOCAL_LIB_ROOT
    export PERL_MM_USE_DEFAULT=1
    perl -MCPAN -e 'install Bundle::CPAN'
    #cpan Text::NSP::Measures::2D::Fisher
    cpan Text::NSP::Measures::2D::Fisher::left
    cpan Class::Std
    cpan DateTime
    wget -P $PERL_LOCAL_LIB_ROOT http://search.cpan.org/CPAN/authors/id/S/SW/SWALTERS/SOAP-WSDL-3.003.tar.gz
    tar -zxf $PERL_LOCAL_LIB_ROOT/SOAP-WSDL-3.003.tar.gz -C $PERL_LOCAL_LIB_ROOT
    perl $PERL_LOCAL_LIB_ROOT/SOAP-WSDL-3.003/bin/wsdl2perl.pl -b $PERL_LOCAL_LIB_ROOT http://www.ebi.ac.uk/europepmc/webservices/soap?wsdl
}

function use_perl_5_16_3 {
    dontUsePerl510
    export PERL_LOCAL_LIB_ROOT=/isitools/perl5.16.3/lib/5.16.3 
    export PERL_MB_OPT=/isitools/perl5.16.3/lib/5.16.3
    export PERL_MM_OPT=INSTALL_BASE=/isitools/perl5.16.3/lib/5.16.3
    export PERL5LIB='/isitools/perl5.16.3/lib/5.16.3/lib/perl5:/isitools/perl5.16.3/lib/5.16.3/x86_64-linux:/isitools/perl5.16.3/lib/5.16.3:/isitools/perl5.16.3/lib/5.16.3/x86_64-linux-thread-multi-ld:/usr/lib64/perl5'
    export PATH=/isitools/perl5.16.3/bin:/isitools/perl5.16.3/lib:$PATH:
    
}
export -f use_perl_5_16_3

function dontUsePerl510 {
    ere_p510="perl5\.10"
    for p in ${PATH//:/ }; do 
        if [[ $p =~ $ere_p510 ]]; then 
            path_remove $p
        fi 
    done
}
export -f dontUsePerl510

function use_perl_518 {
    dontUsePerl510
    export PERL5LIB='/isitools/perl5.18.2/lib/5.18.2/lib/perl5:/isitools/perl5.18.2/lib/5.18.2/x86_64-linux:/isitools/perl5.18.2/lib/5.18.2:/isitools/perl5.18.2/lib/5.18.2/x86_64-linux-thread-multi-ld'
    export PERL5LIB="$PERL5LIB:$PERL_LOCAL_LIB_ROOT:$PERL_LOCAL_LIB_ROOT/lib/perl5"
    export PERL_MB_OPT="--install_base $PERL_LOCAL_LIB_ROOT"
    export PERL_MM_OPT="INSTALL_BASE=$PERL_LOCAL_LIB_ROOT" 
    export PATH="$PATH:$PERL_LOCAL_LIB_ROOT/bin"
    alias cpan="/isitools/perl5.18.2/bin/cpan"
    alias perl="/isitools/perl5.18.2/bin/perl"
    PS1='\A  \h(perl5.18)  \W > '
}
export -f use_perl_518

if [ "${REV:0:1}" == '7' ]; then 
    use_perl_5_16_3
fi

