#!/bin/bash
DEFAULT_PYTHON="3.6.6"
DEFAULT_R="3.1.3"
DEFUALT_PERL="5.10.1"


function remove_regex_els_from_path(){
    regex=$1
    p_list=$2
    p_list_out=""

    for p in ${p_list//:/ }; do
        if ! [[ "$p" =~ $regex ]]; then
            p_list_out="$p:$p_list_out"
        fi
    done
    echo $p_list_out
}

function use_Python(){
    if [ $# -eq 1 ]
    then
        Pver=$1
    else
        Pver=$DEFAULT_PYTHON
    fi

    export PATH=$(remove_regex_els_from_path "Python" $PATH)
    export LD_LIBRARY_PATH=$(remove_regex_els_from_path \
        "Python" $LD_LIBRARY_PATH)

    Pver=Python$Pver
    export PATH=/isitools/$Pver/bin:$PATH
    export LD_LIBRARY_PATH=/isitools/$Pver/lib:$LD_LIBRARY_PATH
    export PYTHONPATH=/isitools/$Pver/bin:$PYTHONPATH
    export VIRTUALENVWRAPPER_PYTHON=/isitools/$Pver/bin/python
    export VIRTUALENVWRAPPER_VIRTUALENV=/isitools/$Pver/bin/virtualenv
}

function use_R() {
    if [ $# -eq 1 ]
    then
        Rver=$1
    else
        Rver=$DEFAULT_R
    fi
    
    R_regex='/R-[0-9]\.[0-9]\.[0-9]/'
    export PATH=$(remove_regex_els_from_path $R_regex $PATH)
    export LD_LIBRARY_PATH=$(remove_regex_els_from_path \
        $R_regex $LD_LIBRARY_PATH)

    export R_HOME_base="/isitools/R-$Rver"
    export R_HOME="$R_HOME_base/lib64/R"
    export PATH=$R_HOME:$R_HOME_base/bin:$PATH
    export R_LIBS=${HOME}/lib/R_Lib:$R_HOME
    export R_LIBS_USER=/isitools/R-packages_$Rver
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$R_HOME/bin:$R_HOME/lib
}

function use_Perl(){
    if [ $# -eq 1 ]
    then
        Pver=$1
    else
        Pver=$DEFAULT_PERL
    fi
    
    Perl_regex='erl5'
    export PATH=$(remove_regex_els_from_path $Perl_regex $PATH)
    export LD_LIBRARY_PATH=$(remove_regex_els_from_path \
        $R_regex $LD_LIBRARY_PATH)

    pl="perl$Pver"
    export PERL5LIB="/isitools/$pl/lib/$Pver/:\
        /isitools/$pl/lib/$Pver/lib/perl5:\
        /isitools/$pl/lib/$Pver/x86_64-linux-thread-multi-ld:\
        /usr/lib64/perl5"
    export PERL_LOCAL_LIB_ROOT=/isitools/perl5.10.1/lib/5.10.1 
    export PERL_MB_OPT=/isitools/perl5.10.1/lib/5.10.1
    export PERL_MM_OPT=INSTALL_BASE=/isitools/perl5.10.1/lib/5.10.1

}



