" This .vimrc autogenerated by Make_my_vi_profile.sh
set nocompatible
syntax on
filetype off
set rtp+=/w4home/jsteill/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.Vim'
Plugin 'Valloric/YouCompleteMe'
Plugin 'NLKNguyen/papercolor-theme'
call vundle#end()
filetype plugin indent on
set tabstop=4 
set softtabstop=4 
set shiftwidth=4
set expandtab 
set foldmethod=indent
set foldlevelstart=99
""#colorscheme molokai
set background=dark
""colorscheme solarized
""colorscheme mayansmoke
set t_Co=256   " This is may or may not needed.
colorscheme PaperColor
set number
set relativenumber
